### ISSUE TITLE
Bot Online pero no ejecuta los comandos

### ISSUE THREAD

**Issue by JorgeDDW** [yagop/telegram-bot#102]
Le puse mi ID de Telegram
sudo_user = {
    4555688, 0
}

guardado, inicio el bot.
Voy a Telegram pero cuando escribo !help, no sucede nada, igual cuando escribo cualquier otro comando.

Algo que yo deba hacer para que funcione?

**Comment by loboaureo** [comment]
Si lo has puesto con tu propio numero de telefono no funcionara, el bot no se contesta a si mismo. Si es otra cosa, ya me temo no puedo ayudarte

**Comment by JorgeDDW** [comment]
Ese era el problema entonces.
Gracias.
