### ISSUE TITLE
Can't logout and change number

### ISSUE THREAD

**Issue by psycholyzern** [yagop/telegram-bot#110]
I cant find correct way to logout and change to another number. How to do that?

**Comment by luksi-reiku** [comment]
I think that is an issue of telegram-cli.

In my case I quit the program and delete the .telegram-cli folder of the home dir

**Comment by cincauhangus** [comment]
this should be documented somewhere..

**Comment by luksi-reiku** [comment]
Maybe, but it is more related to telegram-cli that with telegram-bot

**Comment by cincauhangus** [comment]
That's also true..

**Comment by yagop** [comment]
That is.
