### ISSUE TITLE
How do i find out what are the chat ids that the user is currently in?

### ISSUE THREAD

**Issue by cincauhangus** [yagop/telegram-bot#118]
I'm trying to write a broadcast plugin, but the only current way i'm currently able to get the chat ids the user is in is via the stats plugin, although it's not foolproof since it also includes user ids..

**Comment by yagop** [comment]
I think the other way is to use `chat_info` and store the users, but haven’t tested it.

**Comment by yagop** [comment]
See `id.lua` plugin
