### ISSUE TITLE
Systemd Support

### ISSUE THREAD

**Issue by Synk0** [yagop/telegram-bot#119]
I'm testing Ubuntu 15.04 , and now are not running the upstart , and would like to know if you have as support for Systemd?

**Comment by Synk0** [comment]
I tried to do here but do not understand much about Systemd

[Unit]
Description=Telegram-bot

[Service]
Type=forking

ExecStart=/bin/sh /home/synko/telegram-bot/launch.sh
ExecStop=/bin/sh /home/synko/telegram-bot/launch.sh

**Comment by Synk0** [comment]
telegram.service - Telegram-bot
   Loaded: error (Reason: Bad message)
   Active: inactive (dead)
   Docs: man:foo(1)

Abr 27 01:15:41 synko systemd[1]: [/etc/systemd/system/telegram.service:8] Missing '='.
Abr 27 01:15:56 synko systemd[1]: [/etc/systemd/system/telegram.service:8] Missing '='.
Abr 27 01:16:27 synko systemd[1]: [/etc/systemd/system/telegram.service:8] Missing '='.

**Comment by Synk0** [comment]
[warn] Epoll ADD(1) on fd 0 failed.  Old events were 0; read change was 1 (add); write change was 0 (none): Operation not permitted

**Comment by onotoleonide** [comment]
make telegram.service file in /etc/systemd/system/
```
[Unit]
Description=Telegram Bot
After=syslog.target

[Service]
Type=forking
ExecStart=/root/telegram-bot/launch.sh
Restart=on-abort

[Install]
WantedBy=multi-user.target
```
then run 
systemctl enable /etc/systemd/system/telegram.service
systemctl start telegram.service
