### ISSUE TITLE
Youtube search doesn't work because it uses old API

### ISSUE THREAD

**Issue by onotoleonide** [yagop/telegram-bot#120]
title says it all

**Comment by Brawl345** [comment]
Here is the plugin with the new API: https://gist.githubusercontent.com/Brawl345/e671b60e24243da81934/raw/3f915c93e57a1d600f50df2c554517d4d9c8302f/search_youtube.lua but I modified it so that it sents the description etc.. I'm a LUA beginner, so sorry for bad code :)

**Comment by fedehacker** [comment]
Checkout my pull request #137

**Comment by yagop** [comment]
I have added on `img_google.lua` support for Google API keys (data/google.lua file) youtube plugin will use that as well. Thanks @Brawl345 and @fedehacker for the API entry points.

**Comment by yagop** [comment]
`search_youtube.lua` now uses Google V3 API, set your key on `data/google.lua`
