### ISSUE TITLE
Failed unpacking rock file

### ISSUE THREAD

**Issue by Xenocida** [yagop/telegram-bot#130]
Hello.

I'm trying to install the bot on a Raspberry Pi. Everything is ok till the command:

> $ ./launch.sh install

After some time, it raises an error:

> Error: Failed unpacking rock file: /tmp/luarocks_luarocks-rock-luasocket-3.0rc1-2-8637/luasocket-> 3.0rc1-2.src.rock
> Error. Exiting.

 What can I do?

Thank you in advance!

**Comment by yagop** [comment]
I cant help you too mcuh with this, is a luarocks error.
But maybe you don't have enough space or privileges on `/tmp`

**Comment by yagop** [comment]
![Imgur](http://i.imgur.com/b4aJoC2.jpg)

**Comment by Xenocida** [comment]
![](https://s-media-cache-ak0.pinimg.com/originals/28/af/59/28af59962e58f9efdb342d853597ec58.jpg)
