### ISSUE TITLE
[Request] Add Urban Dictionary plugin

### ISSUE THREAD

**Issue by onotoleonide** [yagop/telegram-bot#131]
http://api.urbandictionary.com/v0/define?term=telegram
I tried to make one, but I suck at coding.

**Comment by Akamaru** [comment]
Hi,
I got a Urban Dictionary plugin from someone, but i forget from where
https://github.com/Akamaru/Mikubot/blob/master/plugins/urban_dictionary.lua

**Comment by onotoleonide** [comment]
Thanks!
