### ISSUE TITLE
Trouble with clean install 

### ISSUE THREAD

**Issue by 220242** [yagop/telegram-bot#132]
![2015-04-29_173749](https://cloud.githubusercontent.com/assets/11466345/7393470/a5eec0bc-ee96-11e4-8fce-2c83228a661d.jpg)

**Comment by 220242** [comment]
cd telegram-bot
rm tg
git clone -b test https://github.com/vysheng/tg.git
cd tg
./configure

**Comment by yagop** [comment]
Solved?

**Comment by 220242** [comment]
yeah
