### ISSUE TITLE
User privileges: how to add ones?

### ISSUE THREAD

**Issue by bdbais** [yagop/telegram-bot#139]
Hi on manual I found:

Those commands require a privileged user, privileged users are defined inside data/config.lua (generated by the bot), stop de bot and edit if necessary.

I tried to add my user on "@test1" inside { } but nothing happend, I notice there is a 0 by default, how to add a priviliged user?

  sudo_users = {
   "@test1",
   "@admin1"
  }

I restarted the bot.

but nothing changed:
tgbot, [05.05.15 15:48]
This plugin requires privileged user

**Comment by rockneurotiko** [comment]
You have to add your ID, not your @name.

If you launch telegram-bot, in the prompt of telegram-cli, you can ask:
    >user_info Name
(You can tab to autocomplete if you had sended some message and the client had readed it)
This will give you the ID:
```
User Name @name (#0000000): <- This #000000 is your id, without the #
        real name: Name
        phone: 
        offline (was online [])
```

**Comment by bdbais** [comment]
I found another way but I reached the same result:

dialog_list ... for name_surname tab autocompletition helped me) 

so why a priviliged user can't add others? is it possible to manage it by tg?

**Comment by rockneurotiko** [comment]
Well... I think that right now you have to modify data/config.lua, but shouldn't be difficult to write a plugin that can add/remove/list sudo users by sudo users.

**Comment by bdbais** [comment]
I will do thx.

**Comment by downeym** [comment]
I am having the same problem:

1. I got the numeric User ID by running `user_info` as describe above. 
2. I then edited my `data/config.lua` file so it reads as shown below.
3. I restarted the bot, but when trying to run `!plugins` from my user account, I got the **"This plugin requires privileged user"** error.

Any ideas what's gone wrong?

**Excerpt of data/config.lua:**
```
  sudo_users = {
    "12345678"
  }
}
return _
end
```


**Error message:**

```
>
Preprocess	stats
Saving user	user:12345678
Preprocess	channels
msg matches: 	^!plugins$
[14:55]  Michael Downey >>> !plugins
Not valid: msg from us
[14:55]  Michael Downey <<< This plugin requires privileged user
User Michael Downey marked read 1 outbox and 0 inbox messages
```

**Comment by downeym** [comment]
Thanks to someone in the chat, figured this out. The correct syntax should not have any "quotes":

```
  sudo_users = {
    12345678
  }
}
return _
end
```
