### ISSUE TITLE
Preguntas

### ISSUE THREAD

**Issue by robotrono** [yagop/telegram-bot#14]
Ya tengo el bot funcionando, muy bueno para el ocio y util también pero tengo las siguientes preguntas:
¿Donde se guarda imagenes del Bot, todo lo que descarga y carga en el Telegram? 
¿Como puedo configurar lo de Twitter? Me sale el siguiente mensaje: You aren't allowed to send tweets
¿Que viene siendo el comando set y get? 

Edit: Otra pregunta, ¿cómo podría dejar el bot en modo background? Podría usar el screen pero mejor preguntar antes.

**Comment by mabregu** [comment]
Se puede borrar la cola de mensajes del bot? Osea los mensajes q fueron enviados al bot...
