### ISSUE TITLE
Como enviar comandos al bot desde el servidor/How to send commands from within the server

### ISSUE THREAD

**Issue by beckmx** [yagop/telegram-bot#143]
Hola a todos, esta es una gran herramienta, alguien sabe como puedo usar el bot para enviar mensajes por ejemplo que sea un cronjob, tengo un cronjob en ruby pero quisiera saber si puedo mandar llamar el telegram-bot para q me mande un mensaje.

English:
Hello everyone, this is such a great tool, I was wondering if there is anyway I can send a message to the bot from another application, I am currently running some task with ruby and would like to send me a message to my telegram number
greetings!

Saludos!

**Comment by yagop** [comment]
Launch tg with `-P <PORT_NUMB>`. Tg will listen incoming commands on that port.

https://github.com/vysheng/tg/issues/255
