### ISSUE TITLE
Request: privileged plugins for channels

### ISSUE THREAD

**Issue by 220242** [yagop/telegram-bot#144]
example
channel one with boobs.lua, danbooru.lua, img_google.lua, help.lua, plugins.lua, etc...
channel two with help.lua, plugins.lua, etc... without boobs.lua, danbooru.lua, img_google.lua.
channel three ...
channel four...
etc...
A lot of thanks in advance.

**Comment by yagop** [comment]
`!plugins disable [plugin] chat` can be used to disable plugins on specific chats.

**Comment by 220242** [comment]
Amazing, I love u! :p
