### ISSUE TITLE
Disabling commands

### ISSUE THREAD

**Issue by viljarb** [yagop/telegram-bot#15]
Hey,
First of all kudos for making awesome bot :+1:
I want to make feature that i can disable certain commands for certain chats. Best way is it to solve with plugin? And where i can get chat id? Can i get like 'user#id'..user_id ?

**Comment by yagop** [comment]
https://github.com/yagop/telegram-bot/pull/45 
You can now disable plugins.
You can add to privileged users the ones that you what to give permission to use them.
