### ISSUE TITLE
Better IMDB plugin?

### ISSUE THREAD

**Issue by psycholyzern** [yagop/telegram-bot#160]
Instead reply with messed up content, can you rearrange so it reply with better formatting? Like new line for title, id, etc?

I tried to look into imdb.lua and I dont know what to be changed LOL

**Comment by rockneurotiko** [comment]
It's a good idea.

A quick change for a better formatting is change:
```
t = t .. k .. ": " .. v .. ", "
```
in https://github.com/yagop/telegram-bot/blob/master/plugins/imdb.lua#L17 for
```
t = t .. k .. ": " .. v .. "\n"
```

Also change the "return t.sub(1, -1)" for "return t"

With this change looks better:
![Uploading Captura de pantalla de 2015-05-17 10-59-48.png…]()

**Comment by psycholyzern** [comment]
Nice.. Can I know what language is this? I know php but cant understand many of the code written. Like the line you mentioned

On May 17, 2015 5:01:01 PM GMT+08:00, rockneurotiko <notifications@github.com> wrote:
>It's a good idea.
>
>A quick change for a better formatting is change:
>```
>t = t .. k .. ": " .. v .. ", "
>```
>in
>https://github.com/yagop/telegram-bot/blob/master/plugins/imdb.lua#L17
>for
>```
>t = t .. k .. ": " .. v .. "\n"
>```
>
>Also change the "return t.sub(1, -1)" for "return t"
>
>With this change looks better:
>![Uploading Captura de pantalla de 2015-05-17 10-59-48.png…]()
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/yagop/telegram-bot/issues/160#issuecomment-102769516

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rockneurotiko** [comment]
This is lua 5 :-)

**Comment by psycholyzern** [comment]
Before this, I made plugin for 8fact and 8crap (you can search them on instagram) 
But I just modified the code from existing plugins because I dont fully understand lua 5. I had to use php api which I wrote myself which scrape and present the data to be collected by the plugin.
It works but doesnt look efficient. Im gonna learn about this language in my pleasure time 😊😊

Btw, "return t" and "return t.sub(1,-1)" what is different of them?
Changing ```t = t .. k .. ": " .. v .. "\n"``` is enough to make new line.

**Comment by rockneurotiko** [comment]
Lua is a great language for this kind of things, go ahead with the learning!

There two returns are equal, but the sub is a function call and will be a little bit (imperceptible) slower.
And yeah, that's the change that I said, change the comma for a new line XD

**Comment by psycholyzern** [comment]
Thanks a lot. 😊😊
