### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by Synk0** [yagop/telegram-bot#166]
it is possible to create a whitelist plug-in where I can put the id of the group allowed.

**Comment by Walkman100** [comment]
Would also be cool if we could whitelist a plugin for a certain group, i.e. the opposite of `!plugins disable <plugin> chat`

**Comment by Synk0** [comment]
But in case I ever want to have all other groups blocked and only released some groups because like it or not disable all groups manually is not legal.

**Comment by soend** [comment]
I like this idea! If i want to disable it in one group chat i just write command `!plugins disable <plugin>`. If i want to disable plugin fully i can call `!plugins disable all <plugin>`. Same will work with enabling, to enable plugin in one chat i call  `!plugins enable <plugin>` and enable to all group chats `!plugins enable all <plugin>`. 

Commands still need little bit thinking, what would be the best syntax? What u think about the idea in general?

**Comment by bb010g** [comment]
@Synk0 Why did you close this?

**Comment by LeartS** [comment]
It surely is a very important feature. I am using a bot on multiple chats, and I'm writing custom plugins for one of those. Having to disable all my custom plugins on all the other chats is really tedious.
