### ISSUE TITLE
Twitter_Send 401

### ISSUE THREAD

**Issue by robotrono** [yagop/telegram-bot#167]
Recién he instalado el Telegram Bot en Ubuntu 14.04 y pues a la hora de poner los codigos de acceso en el plugin pues obtengo ese error.

¿A que se debe? Todo funciona bien en los otros plugins excepto en este. Deshabilite, Habilite, reinicie el Bot y el servidor y no me resulta.

Tengo correctamente los tokens como en la web app de Twitter.

**Comment by rockneurotiko** [comment]
El plugin funciona correctamente, yo acabo de usarlo.

El error 401 es de Unauthorized,  asi que probablemente no has dado permisos de escritura, mira esto quizas te ayude:
http://stackoverflow.com/questions/19095257/using-twython-to-send-a-tweet-twitter-api-error/19196583#19196583

**Comment by robotrono** [comment]
Hmm pues tengo mi aplicación así: 

http://puu.sh/hSK2k/b66eac55ed.png

No se como poner screenshot.

Los consumer_key, consumer_secret, access_token y access_token_secret los he colocado como los tengo, es más hasta renove las keys y pues sigo teniendo el error 401.

**Comment by rockneurotiko** [comment]
Y las tienes bien escritas? Hasta el mas minimo fallito hace que pete (a mi me paso al principio, creo que puse un espacio al final o algo asi), es algo asi:

``` lua
local consumer_key = "aaaaaaaaaaaaaaaaaaaa"  -- 20 caracteres
local consumer_secret = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' -- 42 caracteres
local access_token = "111111111-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" -- 9 numeros -(guion) 40 caracteres
local access_token_secret = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' -- 41 caracteres
```

Prueba a ponerlas en meme.lua y a intentar coger un tweet tuyo:
!tweet name <user>

**Comment by robotrono** [comment]
Saludos nuevamente, que ya coloque las keys, revise que no haya ningun espacio, estoy usando Notepad++, una vez verificado que esten bien copiadas y sin espacio las he colocado en Tweet y twitter_send pero sigue igual con el mismo error. Con Tweet, no arroja nada.

Como sea dejo unas impresiones de pantalla.

Dentro del Chat: 

http://puu.sh/hSMsl/e356f7b6a4.jpg

Mensaje de consola:
http://puu.sh/hSMc5/f79e7cc80a.png

Con Tweet:

http://puu.sh/hSMxR/9b6ea849ba.png

**Comment by rockneurotiko** [comment]
No se que puede ser, pero seguro que es por las claves, los plugins funcionan, los he probado mas de una vez con claves antiguas y unas recien generadas.

Tienes permisos de lectura/escritura en los dos pares de claves? En consumer key/secret y en Access Token? Los dos lo tienen que tener.

Si quieres un poco mas de informacion de porque (y asi quizas podemos intuir un poco mas) cambia la linea 42 de `plugins/twitter_send.lua` por:

``` lua
return "Error: "..response_code .. "\nMessage: " .. json:decode(response_body).errors[1].message
```

**Comment by robotrono** [comment]
Me indica esto: 
Error: 401
Message: Timestamp out of bounds

**Comment by rockneurotiko** [comment]
Al parecer por lo que pone buscando eso es que tienes el reloj local mal XD
[link1](https://twittercommunity.com/t/timestamp-out-of-bounds/287)
[link2](https://twittercommunity.com/t/401-not-authorized-timestamp-out-of-bounds/893)

**Comment by robotrono** [comment]
Vaya ya quedo resuelto, fíjate que sin esa linea no hubiera encontrado el error. Ahora si ni es mucha molestia quiero habilitar el plugin de youtube search,pero creo q hay crear una key, en donde se pone y como se crea?
