### ISSUE TITLE
How to add priviliged user?

### ISSUE THREAD

**Issue by professor93** [yagop/telegram-bot#168]
How to add priviliged user on telegram bot?
Bot is working. 
---
This is "config.lua" file.
---
do local _ = {
  disabled_channels = {},
  enabled_plugins = {
    "9gag",
    "eur",
    "echo",
    "btc",
    "get",
    "giphy",
    "google",
    "gps",
    "help",
    "id",
    "images",
    "img_google",
    "location",
    "media",
    "plugins",
    "channels",
    "set",
    "stats",
    "time",
    "version",
    "weather",
    "xkcd",
    "youtube"
  },
  sudo_users = {
    "6406398"
  }
}
return _
end

---------

**Comment by professor93** [comment]
Please help me on telegram. http://telegram.me/SUPP0RT
my nickname is @SUPP0RT
Thanks

**Comment by rockneurotiko** [comment]
You have to write it as a integer:
sudo_users = {
  6406398
}

**Comment by professor93** [comment]
Thanks, it works

**Comment by professor93** [comment]
Thanks to @sgitkene and rockneurotiko

**Comment by rockneurotiko** [comment]
You're welcome!
