### ISSUE TITLE
Req: Message when user joins a group

### ISSUE THREAD

**Issue by larsf96** [yagop/telegram-bot#169]
Hello,

I thought it would be nice if there is a plugin that automatically sends a message like "@username Welcome to the group" to new users in a group chat. I actually had the idea that you search for a pattern like "added user ..." or something like that, but I don't know how to get the username out of the real name in the bot. I think it would be easy to script so maybe someone can help me with this.

Regards,
Lars

**Comment by psycholyzern** [comment]
damn nice idea. Im not good with lua, so I just gonna wait for it.

**Comment by rockneurotiko** [comment]
I will think about it (but, just as a note, right now tg-cli don't give us the @username, so we can't mentionate them)

The next time, please, don't rename the issue to something completely different, close the first one and open another one.

**Comment by rockneurotiko** [comment]
Closed with #178 check the new plugins :smile:
