### ISSUE TITLE
Google API Youtube

### ISSUE THREAD

**Issue by robotrono** [yagop/telegram-bot#171]
Bueno creo que anteriormente en las versiones anteriores el api para ver el cuadro de Preview en el video youtube no se necesitaba una API o algo así, creo que ahora si se necesita, lo que pasa ahora que pongo un video enlace de youtube el bot mi tira lo siguiente:

http://puu.sh/hTBak/766d3220c5.jpg

Creo que es meter la key api en /data/google.lua pero ya la he colocado así:

do local _ = {"key"}
return _
end

Pero sigue sin funcionar, hay alguna referencia en como crear la api de manera a que llegue funcionar con el bot?

**Comment by rockneurotiko** [comment]
El plugin no estaba rediseñado para la API v3, y ahora ya no dejan usar la v2, por lo que ahora las keys son obligatorias y las peticiones son distintas.

Lo he modificado para que ya se puedan hacer las peticiones con la version 3 en el commit 8c88dbf3f615b510e7fad11d4d1d65cf65d63d38

 Las keys no se ponen como lo estas poniendo tu, sino asi:

```
do local _ = {api_keys = {"key1", "key2", "key3"}}
return _
end
```

Y las claves tienes que generarlas aqui: https://console.developers.google.com/ y tambien dar permiso a la API de Youtube en esa misma consola.

**Comment by robotrono** [comment]
¿Que tipo de clave debe de ser? ¿Navegador o Servidor?

**Comment by rockneurotiko** [comment]
Servidor :)

**Comment by robotrono** [comment]
Gracias, fijate que estoy probando el "search_youtube.lua" y pues creo que no entiendo mucho, le pongo !youtube palabraabuscar y siempre me manda lo siguiente:

http://puu.sh/hTXyD/7e4fd433cc.jpg

**Comment by Gurskiy** [comment]
same problem with 
![image](https://cloud.githubusercontent.com/assets/9033473/7723779/dcf587c2-fef3-11e4-843b-a6742e2b8d51.png)

**Comment by rockneurotiko** [comment]
@robotrono @Gurskiy Fixed in 1279bd61d98b92db75ee4d965273e0e2f8b863f1
Thanks for reporting!
