### ISSUE TITLE
Floo 

### ISSUE THREAD

**Issue by Gurskiy** [yagop/telegram-bot#172]
![image](https://cloud.githubusercontent.com/assets/9033473/7722245/1692957c-fee7-11e4-9d02-3d411b22a579.png)
Hello. How can i fix this?

**Comment by Gurskiy** [comment]
simply by disabling echo plugin? :)

**Comment by rockneurotiko** [comment]
!plugin disable echo :smile: 

The error is of tg-cli, and probably is because the number of petitions :)
