### ISSUE TITLE
Nueva Instalación, problema con comandos

### ISSUE THREAD

**Issue by robotrono** [yagop/telegram-bot#181]
Tengo el siguiente problema, recién acabo de instalar el bot, pero tengo el siguiente problema:
http://puu.sh/hV4NI/22ff5dbc02.png
Escribo !help y no lee los comandos ahi dejo la screen.
¿A que se debe?

Volví a iniciar el bot, pero algo note fue que carga doble el data/google.lua
```
Allowed user: 0
Loading plugin  9gag
Loading plugin  eur
Loading plugin  echo
Loading plugin  btc
Loading plugin  get
Loading plugin  giphy
Loading plugin  google
Loading plugin  gps
Loading plugin  help
Loading plugin  images
Loading plugin  img_google
Data loaded from file   data/google.lua
Loading plugin  location
Loading plugin  media
Loading plugin  plugins
Loading plugin  channels
Loading plugin  set
Loading plugin  stats
Loading plugin  time
Loading plugin  version
Loading plugin  weather
Loading plugin  xkcd
Loading plugin  youtube
Data loaded from file   data/google.lua
User Akira Perez updated username
User Akira Perez updated photo
User hestia is the Bestia updated username
User hestia is the Bestia updated photo
> Not valid: old msg
[04:32]  Akira Perez >>> dd
```

Edit: Después de un cierto tiempo (10 min) ya reconoce los comandos. Algo que nunca me habia pasado con otros servidores en ubuntu 14.04 x64

**Comment by rockneurotiko** [comment]
Por la imagen parece que lo esta viendo como mensajes antiguos..

Cambia las lineas de la 51 a la 54 de `bot/bot.lua` por:
```
if msg.date < now then
    vardump(msg.date)
    vardump(now)
    print('\27[36mNot valid: old msg\27[39m')
    return false
end
```

A ver que sale :)

**Comment by robotrono** [comment]
Reinicie y aparece esto:
```
> 1432197934
1432198132
Not valid: old msg
[04:45]  Akira Perez >>> !help
> 1432197937
1432198132
Not valid: old msg
[04:45]  Akira Perez >>> !help
```

**Comment by rockneurotiko** [comment]
Tienes el reloj del sistema adelantado, segun eso, el programa se inicio en (estan en GMT):

Thu, 21 May 2015 08:48:52 GMT

Y el mensaje (segundo) lo recibio:
Thu, 21 May 2015 08:45:37 GMT

Por lo que mas o menos tienes el reloj adelantado unos 3 minutos XD

**Comment by robotrono** [comment]
wow este servidor en verdad me lo entregan con un horario modificado, muchas gracias @rockneurotiko
