### ISSUE TITLE
block webp in download_media.lua

### ISSUE THREAD

**Issue by Akamaru** [yagop/telegram-bot#182]
maybe block webp (stickers) in download_media.lua?

**Comment by rockneurotiko** [comment]
`plugins/media.lua` works when you give him a link, not a direct media (sending a sticker, for example)

Are you having any problem with that plugin? :S

**Comment by Akamaru** [comment]
I don't mean [media.lua](https://github.com/yagop/telegram-bot/blob/master/plugins/media.lua), I mean [download_media.lua](https://github.com/yagop/telegram-bot/blob/master/plugins/download_media.lua).
Everytime a user sends a sticker, the bot save it in a new file. I got in the last 7 days over 4k stickers in the download folder. That's why I want to block webp/stickers.

**Comment by rockneurotiko** [comment]
Sorry! 
Maybe we can add a setting file to ignore files by extension/mimetype?

**Comment by yagop** [comment]
The purpose of `download_media.lua` is to download files. 
The info provided by message is the media type:
``` lua
media = {
    type = "document"
  }
```
Stickers are documents, comment the line.

**Comment by Walkman100** [comment]
Or `!plugins disable download_media` :stuck_out_tongue_winking_eye:
