### ISSUE TITLE
request : wrong command answer

### ISSUE THREAD

**Issue by HKraToS** [yagop/telegram-bot#184]
when a user writes a wrong command like : !command bot send a answer for correct commands like : !help for see commands

**Comment by yagop** [comment]
Sadly should be done per plugin.

I started to code plugins with info if fails, see `wiki.lua`.

**Comment by HKraToS** [comment]
i found a way for that with bot.lua , but its have some problems...
but its worked for wrong commands at all for example !hel or ... but for !wiki ... sadly no 
http://pastebin.com/gMWAa6z4
i started learning lua, and i have another request, can i ask in here or i have to open another issues ?
