### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by sp-99** [yagop/telegram-bot#187]
![lol](https://cloud.githubusercontent.com/assets/9088755/7783966/e88f2f10-014c-11e5-9da1-2fb41cfb3d4b.png)
It does not ask for the phone number like it says it should when I run launch.sh.

**Comment by rockneurotiko** [comment]
Can you explain a little bit more how did you installed it and executed?

That seems to be a tg error.

**Comment by sp-99** [comment]
I followed these instructions: http://prntscr.com/78fbpc
And with the final one it did this: ![lol1](https://cloud.githubusercontent.com/assets/9088755/7784092/4d401d08-0151-11e5-8ece-81b675ff6fe9.png) and paused at the end of that screenshot for about 30 seconds and then continued as you can see from my orgional post.

**Comment by rockneurotiko** [comment]
Try to do this from the telegram-bot directory:
``` bash
# Clean configuration of tg
> rm -r ~/.telegram-cli  
> ./tg/bin/telegram-cli -k ./tg/tg-server.pub -l 1 -E
```
Does it gives you the same error?

**Comment by sp-99** [comment]
It comes up with this:
![lol3](https://cloud.githubusercontent.com/assets/9088755/7784218/890393c0-0155-11e5-9268-0457f2266e34.png)

**Comment by rockneurotiko** [comment]
Hmmm... I'm going to start a clean virtual machine, test it and tell you :)
Seems that is tg who breaking. (tg is not this project, is [this](https://github.com/vysheng/tg))

**Comment by sp-99** [comment]
Thanks :)

**Comment by sp-99** [comment]
Any update?

**Comment by HKraToS** [comment]
try to delete your telegram-cli and relaunch the ./laucn.sh install

**Comment by sp-99** [comment]
Still the same :(

**Comment by HKraToS** [comment]
did you installed libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make unzip git redis-server ?
if yes , i have to say try to reinstall your ubuntu :(

**Comment by rockneurotiko** [comment]
I've made a fresh install and all gone well.
Things that I've made (just follow the instructions, but...)
```
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make unzip git redis-server g++
cd $HOME
git clone https://github.com/yagop/telegram-bot.git
cd telegram-bot
./launch.sh install
./launch.sh
```

**Comment by nebulakl** [comment]
Which version of ubuntu are you using?
In fact, at first I used ubuntu 15.04 64bit to install the bot and it gave me the exact same error as yours and after I downgraded to 14.04 32bit everything just works flawlessly.

**Comment by voiser** [comment]
Are you using the latest tg-cli version? There was a bug that produced this behaviour but it is now fixed in the master branch.

**Comment by yagop** [comment]
This is a tg issue.
Try removing `./telegram-cli` also.

**Comment by sp-99** [comment]
I tried Linux mint and it worked... O.o
