### ISSUE TITLE
can't tweet

### ISSUE THREAD

**Issue by nebulakl** [yagop/telegram-bot#190]
I'm on ubuntu 14.04, carefully followed the instructions and configured the bot. but when i try to tweet, it always return "Error: sslv3 alert handshake failure" error

![image](https://cloud.githubusercontent.com/assets/12024936/7787064/4987c0bc-0228-11e5-92c1-bbf3f69dbcab.png)

besides, !tweet plugin does not work at all, it just returns nothing even though i've enabled it.

**Comment by psykomantis** [comment]
Hi! Do you edited the first lines of `twitter_send.lua`? 
I didn't dig too much with this plugin, but I think it may be an authentication problem, you should check how to authenticate to the API maybe [this] (https://dev.twitter.com/overview/documentation) link could help you. 
Previously I was referring to these lines: 

``` 
    local consumer_key = ""
    local consumer_secret = ""
    local access_token = ""
    local access_token_secret = ""
```

**Comment by nebulakl** [comment]
Yes I do. Otherwise it should return something like "xxxx is empty, write it in plugins/twitter_send.lua"

**Comment by rockneurotiko** [comment]
I've been testing.
First of all, you had reason, tweet plugin didn't catch some errors, now it does :)
But I can tweet with twitter_send. Can you write the trace that gives you when execute ./launch.sh?
Is something like:
```
> ./launch.sh
Telegram-cli version 1.2.0, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 1.2.0
[...] More info
```

**Comment by nebulakl** [comment]
Problem solved after I connect with VPN, maybe I was experiencing Man-in-the-middle attack before.
Thanks for help:)
