### ISSUE TITLE
New image search !img

### ISSUE THREAD

**Issue by Josepdal** [yagop/telegram-bot#194]
Google only give us 100 queries. Can anyone search about duckduckgo flickr or another service to do that?

**Comment by HKraToS** [comment]
i read in somewhere if you can add a user-agent to your but you can pass the 100 queries

**Comment by Josepdal** [comment]
Dont know how anyone know more about that??

**Comment by rockneurotiko** [comment]
Currently img_search take your API codes from the file `data/google.lua` (you can see it in line 25 of `plugins/img_google.lua`)
You can see some answers to similar problems [here](https://github.com/yagop/telegram-bot/issues/171).
The answers are in spanish... If google transale is not enough I can tranlate :)

**Comment by rockneurotiko** [comment]
(miss click and closed XD)

**Comment by Josepdal** [comment]
Ok finally I will use different keys to provide more query requests. Thanks rock :+1:

**Comment by rasadeyan** [comment]
Hi,
I was wondering if u would tell us how to solve that ?! Beacause my bot has thousands of queries for image but i cant pass the googles restricted queries!

**Comment by Josepdal** [comment]
In data/google.lua you can put a lot of different api keys. If you have a comunity using yout bot, ask if they can share their api key. I will do it... Api keys will get randomly, but you can add keys like: first, using 1 key, when it give you error 403, use 2nd api key... try to get most api keys as you can.

**Comment by rockneurotiko** [comment]
Also, like I said to @Josepdal in private, I don't really know if that will be a solution.
If after all there are still the 100 search limit, let's search another image search (but all the big ones have API limits for free accounts, bing have 5000 per month, for example).

**Comment by rasadeyan** [comment]
Ok! Thanks 4 Ur responde! As a guess how many keys doour bot need to download 30 pics in a minute ?!

**Comment by Josepdal** [comment]
Make calculations, but... 30 pics in a minute??? OMG!! rlly? get most api keys as you can its better than nothing haha

**Comment by rockneurotiko** [comment]
@rasadeyan you would need like 432 API keys XD
```
>>> (30 * 60 * 24) / 100  # 30 in a minute, for 60 minutes in a hour for one day divide by number of queries by key XD
432.0
```

**Comment by rasadeyan** [comment]
OMG!!!
Thanks!

**Comment by HKraToS** [comment]
@yagop  its a big problem for creating and adding api keys, can you try to add a user agent to img search ?

**Comment by rasadeyan** [comment]
I think using multiple user agents can solve my problem so what is yoir idea ?!
Witch user agents do you prefer to use ?!

**Comment by rockneurotiko** [comment]
Where did you read that with multiple agents you solve the problem?

**Comment by yagop** [comment]
No, if API Key is provided, Google wont look for UserAgent.
`img_google.lua` uses a random API key from `data/google.lua`
https://github.com/yagop/telegram-bot/blob/master/plugins/img_google.lua#L25

**Comment by rasadeyan** [comment]
Thank YOU! I'll check it!

**Comment by rasadeyan** [comment]
You said if we remove the api key may be we can use user agents to solve over problem!
Am i roght ?!
