### ISSUE TITLE
How to get the files from master without rewrite important files?

### ISSUE THREAD

**Issue by psycholyzern** [yagop/telegram-bot#196]
Sorry if the title is confusing.
I want to get the files from git master to keep updating my existing files on the server with the newly commited file on github. Im afraid my existing data such as disabled plugin, sudo user, phone number, being rewritten.

Is there any safer way to do this?

**Comment by voiser** [comment]
git won't overwrite any modified file when pulling, you will have to backup, reset and restore the backup. A good option is git stash:

git stash
git pull origin master
git stash pop

**Comment by Walkman100** [comment]
The data files that contains disabled plugins, sudo users, and phone numbers are ignored by git anyway, so it is completely safe to just do `git pull` on it's own...

Only if you have modified plugins, then you can still do `git pull`, but it will tell you that some files weren't updated because they have been modified

**Comment by psycholyzern** [comment]
@voiser so I just need to type them in telegram-bot directory right?

**Comment by psycholyzern** [comment]
Is this ok @voiser ?

![](http://s27.postimg.org/6hjcf32gz/Screenshot_2015_05_26_09_18_57.png)

**Comment by psycholyzern** [comment]
@Walkman100 what is differences between your method and @voiser 's?

**Comment by Walkman100** [comment]
> Edit: new plugins doesnt work

According to the screenshot it seems like it should work...

> @Walkman100 what is differences between your method and @voiser 's?

They are the same method, just @voiser said to make a backup before pulling the changes, then restore the backup afterwards. I'm saying that unless you've modified plugins, you don't need to do anything other than pulling the changes.

**Comment by psycholyzern** [comment]
@Walkman100 so, I need to enable the new plugin manually?
I got some modified plugins.

**Comment by Walkman100** [comment]
yeah, it seems like your modified plugins were restored succesfully :+1:

> so, I need to enable the new plugin manually?

yes. It shouldn't enable new plugins automatically.

**Comment by psycholyzern** [comment]
Nice.. Thank you for both of you. 😀😀😀
