### ISSUE TITLE
Bump the tg version.

### ISSUE THREAD

**Issue by rockneurotiko** [yagop/telegram-bot#203]
Bump the tg version, now it's pointing to 1.2.0 version [this](https://github.com/vysheng/tg/tree/01f5d9a3b671edc15a5cff285601115845489985).

Also, in the new version, we'll have to add this to install instructions:
```
libjansson-dev libpython-dev
```

**Comment by yagop** [comment]
Yes, its on the priorities top.

BTW I think we should use at last 2 branches. The develop one and the
master one, only for merging from develop and releasing versions.

Other branches like testing could be cool

**Comment by rockneurotiko** [comment]
Agree with the branches approach =D
