### ISSUE TITLE
Joing groups via link

### ISSUE THREAD

**Issue by payamohajeri** [yagop/telegram-bot#210]
It could be useful if we can join groups when their links shared with bot.
I couldn't find this feature in your bot. if it's implemented, please help me in that.

**Comment by payamohajeri** [comment]
it seems telegram-cli now has implemented this feature. as mentioned in this commit (https://github.com/vysheng/tg/commit/0723957e930302890a82c3e482e75d269187c8f8) they have push it 3 days ago :).

**Comment by psycholyzern** [comment]
I made this on the day the function implemented. 
https://raw.githubusercontent.com/psycholyzern/telegram-bot/a3aac98b81f5d05b8dc81121059321deae8715f7/plugins/inviteme.lua

**Comment by psycholyzern** [comment]
mind to close this issue if solved?

**Comment by payamohajeri** [comment]
thanks :)
