### ISSUE TITLE
search_youtube plugin not working

### ISSUE THREAD

**Issue by bluehood** [yagop/telegram-bot#217]
I was never able to use the search_youtube plugin. It exits due to "HTTP Error". Copy-pasting in my browser the request URL it uses to fetch the video, this is what I get:
```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

I'm not familiar with google apis so I can't think of a solution.

**Comment by rockneurotiko** [comment]
Do you have API keys?
If don't see the issue #171, but becareful, it's in spanish! XD

**Comment by bluehood** [comment]
API keys, that was it. I was able to understand enough from #171 to make it work. Here's a guide for other people who might have this problem and don't know how to fix it. I suggest you mention that the search_youtube plugin needs google API keys in the README file of the project.

- generate google API keys
  - go [here](https://console.developers.google.com)
  - click on *create a new project* if you don't have one
  - go to *APIs and auth -> APIs -> Youtube Data API* and click **enable API**
  - go to *APIs and auth -> Credentials* and click **Create new Key**
- copy the text after *API key* and paste it in telegram-bot's configuration file data/google.lua. the end result should look like this:
```
### data/google.lua ###
do local _ = {api_keys = {"pasteyoukeyhere"}}
return _
end
```
- restart telegram-bot
