### ISSUE TITLE
Sending messages

### ISSUE THREAD

**Issue by cun** [yagop/telegram-bot#22]
Hi there! 

Firstly, seriously nice work with this, It's totally reliable and simple to script for.
However I have a small issue. I'm wanting to push alerts to the process, and have the bot read them.

I've started by creating an API where the bot can check the alerts and if one exists it posts it in the chat however I need to make this check every n'th minute or second. 

How can i create a plugin that checks every x, without it looking for a users interaction or input via the chat. 

Cheers
Dan.

**Comment by cun** [comment]
This is working perfectly now, and has been for a week. Thanks yagop!

**Comment by yagop** [comment]
I close the issue, at the moment cron is disabled by default.
