### ISSUE TITLE
Send audio as voice message?

### ISSUE THREAD

**Issue by Synk0** [yagop/telegram-bot#222]
The mobile app and desktop client treat received audio files and voice messages differently.
Is there a way using telegram-cli to send an audio file (ogg and/or mp3) as a voice message?

https://github.com/vysheng/tg/issues/420

**Comment by rockneurotiko** [comment]
Right now is impossible, lua library only give us a set of function that you can see [here](https://github.com/vysheng/tg/blob/master/README-LUA), and the only way to send sound is with send_audio, that will send it as a normal audio.

Even in the issue that you put, ask tg to implement that option, so, we need to wait until tg have implemented and the lua library let as do it :smile:

**Comment by behnamoh** [comment]
Last comments were almost a 1 year ago. Has telegram implemented this feature yet?
It would be very nice to send audio files as voice messages.

**Comment by danielnieto** [comment]
Last comments were almost a 1 year ago. Has telegram implemented this feature yet?
It would be very nice to send audio files as voice messages.

**Comment by francocruces** [comment]
Last comments were almost a 1 year ago. Has telegram implemented this feature yet?
It would be very nice to send audio files as voice messages.
