### ISSUE TITLE
link previews are massively annoying (e.g. tex plugin)

### ISSUE THREAD

**Issue by bluehood** [yagop/telegram-bot#234]
I think you can use the tg flag `--disable-link-preview` as in this issue [here](https://github.com/vysheng/tg/issues/502)

**Comment by rockneurotiko** [comment]
If you don't like the previews, modify the launch.sh with that flag, but other ones like it (I like it in some plugins XD)

**Comment by bluehood** [comment]
Yep I agree, I'm not suggesting to remove previews altogether, just that they don't make sense for some plugins. For example, the tex plugin provides an URL you can visit to edit the code you just generated. nobody needs a preview of that :P 

I see that --disable-link-preview can only be used application-wise, I didn't think about it xD
Thanks for the tip about launch.sh!

**Comment by rockneurotiko** [comment]
Yeah, I'm with you, with some plugins is annoying, for example, in the python library when you send a message you can set a flag to disable the link preview, I didn't read anything like that in the lua library, I hope that they add it :smile:

**Comment by bluehood** [comment]
so I added `--disable-link-preview` at the end line 106 of launch.sh (right where the telegram-cli is started) and it works like a charm

**Comment by Akamaru** [comment]
but it does'nt work, if you start the bot as a daemon :/

**Comment by bluehood** [comment]
I have never used it as a daemon, but maybe I can help. What's your configuration to run it as a daemon? do you use upstart? 
Eventually what's executed is always `launch.sh` (i.e. the command is `exec /bin/sh /home/blue/telegram-bot/launch.sh`) so it's weird the bot behaves differently.

Is the daemon started using the same `launch.sh` as the normal process?

**Comment by buzz3rs** [comment]
hello, if i wanted to disable-link-preview
how can i add it to launch.sh ?

**Comment by bluehood** [comment]
Hello,
as written above: you have to append `--disable-link-preview` to the second-to-last line of `launch.sh` (the line that runs `telegram-cli`), so that the telegram client always disables link previews. Note that this is a configuration pertaining to vysheng's telegram client ([tg](https://github.com/vysheng/tg)) and does not have anything to do with yagop's `telegram-bot`.
