### ISSUE TITLE
Sending Stickers

### ISSUE THREAD

**Issue by rasadeyan** [yagop/telegram-bot#237]
I was wondering if you would mind tell me how to send stickers ?!

**Comment by rasadeyan** [comment]
I dont want to send all the package! I just need to post one of the pictures in stickers like a person when uses a sticker !?

**Comment by rockneurotiko** [comment]
You can send a .webp file as document.

**Comment by rasadeyan** [comment]
It sends just an sticker?! Or sends all of the package ?!

**Comment by rockneurotiko** [comment]
If you send a webp file as document, it will be sended as a sticker.

**Comment by rasadeyan** [comment]
Ok thanks

**Comment by yagop** [comment]
Can be closed?

**Comment by rasadeyan** [comment]
Yeap, thanks

**Comment by ollpu** [comment]
@yagop you going to close this?
