### ISSUE TITLE
--disable-extf

### ISSUE THREAD

**Issue by psycholyzern** [yagop/telegram-bot#242]
The thing in the title said can be found in https://github.com/yagop/telegram-bot/blob/master/launch.sh#L78 

I think ```--disable-extf``` is broken as the image below shown
![](http://s22.postimg.org/ian9hsc9t/IMG_20150607_231644.jpg )

I tried on 64mb and 128mb vps. Both will have result broken by that error. Removing ```--disable-extf``` will make a successful compiling process. Compiling tg on 128mb vps is successful but not on 64mb vps because the process got killed because not enough memory.

So I think the parameter is not relevant for now.

**Comment by rockneurotiko** [comment]
I've added that flag because in my raspberry (first model B, 256 RAM memory) didn't compile with the normal configure, and I founded the issue vysheng/tg#384 in tg project that explained that it was a RAM problem and to use that flag, I tried and worked.
Maybe only works with ARM processor, but in my raspberry, without that flag, don't compile.

**Comment by psycholyzern** [comment]
I successfully compiled with ```--disable-extf``` on Telegram-cli v1.2.0..
But after pulled version 1.3.2 and try to compile with ```--disable-extf```, I got error like in the screenshot posted before.

And yes, it is on same 64mb vps.

**Comment by rockneurotiko** [comment]
I'm gonna try to compile the new version and I'll update here :smile:

**Comment by psycholyzern** [comment]
XD nice

**Comment by rockneurotiko** [comment]
I've been testing, and yeah, first of all, --disable-extf gives error in the make, I guess that they have something strange.
Second, after one hour, and using the solution in vysheng/tg#545 I've builded, I will change the launch.sh :smile: 
Thanks!

**Comment by yagop** [comment]
#243
