### ISSUE TITLE
location plugin not working anymore

### ISSUE THREAD

**Issue by bluehood** [yagop/telegram-bot#251]
I noticed today that everytime I issue `!loc (location)` I receive the following error:
`*** lua: plugins/location.lua:20: attempt to call global 'get_latlong' (a nil value)`

**Comment by psycholyzern** [comment]
you typed exactly like this -> ```!loc (location)``` ?

**Comment by bluehood** [comment]
ahah come on now give me some credit xD

![capture](https://cloud.githubusercontent.com/assets/10999034/8077901/e37b241e-0f59-11e5-8abb-a0bcf8517d4d.png)

**Comment by psycholyzern** [comment]
well, I dont.have that problem

![](http://s7.postimg.org/ddxtbwyob/Pics_Art_1433939324491.jpg)
![](http://s7.postimg.org/qjdbi0sjv/Pics_Art_1433939358365.jpg)

**Comment by rockneurotiko** [comment]
Me neither...
What plugins do you have enabled @bluehood ??

**Comment by bluehood** [comment]
here they are. I have this problem with the latest yagop/telegram-bot/master commit on Debian stable release (64-bit).

plugin9gag
plugins/eur
plugins/echo
plugins/giphy
plugins/google
plugins/gps
plugins/help
plugins/images
plugins/img_google
plugins/location
plugins/plugins
plugins/stats
plugins/version
plugins/weather
plugins/xkcd
plugins/id
plugins/pokedex
plugins/vote
plugins/roll
plugins/imdb
plugins/dogify
plugins/wiki
plugins/magic8ball
plugins/hackernews
plugins/isup
plugins/quotes
plugins/webshot
plugins/banhammer
plugins/search_youtube
plugins/tex
plugins/qr
plugins/meme
plugins/remind
plugins/face
plugins/lyrics

**Comment by rockneurotiko** [comment]
There is the fail.
location plugin uses a function in `time` plugin (https://github.com/yagop/telegram-bot/blob/8f00b554a2013ebe061c9a6eeadf1bb4033fc932/plugins/time.lua)
That plugin is in the master branch, but you don't have it in that list, so, something wrong happened, because you don't have it xD

**Comment by bluehood** [comment]
I disabled it because it doesn't display the correct time (as per #126 ).

If location depends on time it should be explicitly written somewhere, and it shouldn't be possibile to disable time without disabling location too. I'd say this is a bug :p

**Comment by rockneurotiko** [comment]
Yeah, I've disabled time, and re-runing the bot, and fail with the same.
@yagop Maybe the general functions should be extracted to other file, and actually don't have general functions in any plugin xD

**Comment by yagop** [comment]
Could be duplicated. One fault is the ability to load functions from other plugins.
