### ISSUE TITLE
Error 1 while compiling

### ISSUE THREAD

**Issue by Pe46dro** [yagop/telegram-bot#267]
```log
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libm.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [bin/telegram-cli] Error 1
```

I still get this error while I try to execute the command ./launch.sh

**Comment by yagop** [comment]
Seems [telegram-cli](https://github.com/vysheng/tg) problem, please report problem there.

**Comment by Pe46dro** [comment]
Solved at <a href="https://github.com/vysheng/tg/issues/647">@tg #645</a>
I edited the ```launch.sh``` at line 80 like this
```shell
cd tg && ./configure --disable-python && make
```
I will edit launch for solve it nad create a pull request

**Comment by rockneurotiko** [comment]
If you had to disable python, means that you didn't installed properly the dependencies.
