### ISSUE TITLE
noobquestion

### ISSUE THREAD

**Issue by swagerigi** [yagop/telegram-bot#280]
Those commands require a privileged user, privileged users are defined inside `data/config.lua` (generated by the bot), stop the bot and edit if necessary.

How?

I always get:
This plugin requires privileged user

can someone give me a example please?

**Comment by tguser13** [comment]
/home/user/telegram-bot/data/config.lua

},
  sudo_users = {
    123456789
  }

123456789 is the ID of a user who will get the permissions.
!id should return you own if sent to your bot.

**Comment by swagerigi** [comment]
thanks very much tguser13

!id was the command i was looking for!

**Comment by bb010g** [comment]
Please close this issue if it's resolved.
