### ISSUE TITLE
Not valid: old msg

### ISSUE THREAD

**Issue by alek911** [yagop/telegram-bot#288]
hello everybody
When I wrote to the bot (!help, for example) I dont receive reply and in console I see:

telegram-bot@BlackStar:~/telegram-bot$ ./launch.sh
Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.0.3
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
Telegram-cli uses libpython version 2.7.9
I: config dir=[/home/telegram-bot/.telegram-cli]
Allowed user: 30113870
Loading plugin  9gag
Loading plugin  eur
Loading plugin  echo
Loading plugin  btc
Loading plugin  get
Loading plugin  giphy
Loading plugin  google
Loading plugin  gps
Loading plugin  help
Loading plugin  id
Loading plugin  images
Loading plugin  img_google
Data loaded from file   data/google.lua
Loading plugin  location
Loading plugin  media
Loading plugin  plugins
Loading plugin  channels
Loading plugin  set
Loading plugin  stats
Loading plugin  time
Loading plugin  version
Loading plugin  weather
Loading plugin  xkcd
Loading plugin  youtube
Data loaded from file   data/google.lua
Not valid: old msg
[09:54] ale >>> !help
>

Con someone help me? Thankyou

**Comment by alek911** [comment]
for unknown problem during the install process the script exit becouse luarocks can't install luacrypto, lbase64, etc etc.

I have installed it manually (i do: ./launch.sh install , note what doesn't install, install manually, redo the install script . for every module that install process can't install in auto)
Now the bot start but for every command reply in console with the log that I have posted in OP.
Is possible that I haven't install some modules? There is a list of the luarocks modules required? 
Sorry for my bad english

**Comment by yagop** [comment]
Bot doesn't answer console commands. Only sended by Telegram.

**Comment by alek911** [comment]
Yes, I know. but my bot doen't respond in telegram. when I send a command iun telegram bot doesn't respond but in console say "Not valid: old msg"

**Comment by yagop** [comment]
If this happens every time you receive a message, maybe your system time differs from the date msg was sended. Check your time!

**Comment by alek911** [comment]
but..lol. It's to day that I stufy for why not working.. and at the end of all is a clock problem. Thankyou @yagop .. now is ok (for install bot I have do a fresh debian installation and I don't have set the correct time..)

Sorry for the topic!!

**Comment by yagop** [comment]
:thumbsup:

**Comment by regalstreak** [comment]
thanks!
