### ISSUE TITLE
make: *** [bin/tl-parser] Error 1

### ISSUE THREAD

**Issue by IHA114** [yagop/telegram-bot#294]
In centos after run this command 
./launch.sh install

Display This Error

/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:897: undefined reference to `rpl_malloc'
/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:897: undefined reference to `rpl_malloc'
objs/tl-parser.o: In function `new_tree_node_tl_type':
/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:894: undefined reference to `rpl_malloc'
/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:894: undefined reference to `rpl_malloc'
objs/tl-parser.o: In function `new_tree_node_tl_var':
/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:901: undefined reference to `rpl_malloc'
objs/tl-parser.o:/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:901: more undefined references to `rpl_malloc' follow
objs/tl-parser.o: In function `tl_add_constructor':
/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:1169: undefined reference to `rpl_realloc'
/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:1156: undefined reference to `rpl_malloc'
/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:1130: undefined reference to `rpl_malloc'
objs/tl-parser.o: In function `tl_parse':
/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:2704: undefined reference to `rpl_malloc'
objs/tl-parser.o: In function `tl_init_parse_file':
/home/telegram-bot/tg/tgl/tl-parser/tl-parser.c:340: undefined reference to `rpl_malloc'
collect2: ld returned 1 exit status
make: *** [bin/tl-parser] Error 1
Error. Exiting.

???

**Comment by yagop** [comment]
This a [tg](https://github.com/vysheng/tg) issue, please report there.
