### ISSUE TITLE
Why offset parameter don't work?

### ISSUE THREAD

**Issue by CatFox** [yagop/telegram-bot#297]
When I input: https://api.telegram.org/bot9455....kwtc/GetUpdates?offset=4
I get:
{"ok":true,"result":[{"update_id":...
"message":{"message_id":2,"from":{"id":...
"message":{"message_id":3,"from":{"id":...
An offset parameter higher than latest update_id!

**Comment by rockneurotiko** [comment]
I don't know why you ask here (this project don't use bot API), but the offset works, just set it as last update_id + 1
(update_id, not message_id)
