### ISSUE TITLE
Missing dependencies for feedparser: luaexpat

### ISSUE THREAD

**Issue by EklavyaFCB** [yagop/telegram-bot#298]
I get the following error after launching the ./launch.sh install command in /telegram-bot directory:

Installing https://rocks.moonscript.org/feedparser-0.71-3.src.rock...
Using https://rocks.moonscript.org/feedparser-0.71-3.src.rock... switching to 'build' mode

Missing dependencies for feedparser:
luaexpat 

Using https://rocks.moonscript.org/luaexpat-1.3.0-1.src.rock... switching to 'build' mode

Error: Failed installing dependency: https://rocks.moonscript.org/luaexpat-1.3.0-1.src.rock - Could not find expected file expat.h, or expat.h for EXPAT -- you may have to install EXPAT in your system and/or pass EXPAT_DIR or EXPAT_INCDIR to the luarocks command. Example: luarocks install luaexpat EXPAT_DIR=/usr/local
Error. Exiting.

So I try to install expat, but:

$ brew install expat
Warning: expat-2.1.0_1 already installed

brew list expat
/usr/local/Cellar/expat/2.1.0_1/bin/xmlwf
/usr/local/Cellar/expat/2.1.0_1/include/ (2 files)
/usr/local/Cellar/expat/2.1.0_1/lib/libexpat.1.dylib
/usr/local/Cellar/expat/2.1.0_1/lib/pkgconfig/expat.pc
/usr/local/Cellar/expat/2.1.0_1/lib/ (2 other files)
/usr/local/Cellar/expat/2.1.0_1/share/man/man1/xmlwf.1

**Comment by yagop** [comment]
Install the headers, expat-dev or something like that

**Comment by zifeo** [comment]
Problem might come from Brew which is installing under `version_revisionNumber` format. You can solve this by installing Expat from sources.

**Comment by EklavyaFCB** [comment]
Solved issue by:

Uninstalling expat using brew:

$ brew uninstall expat
$ brew cleanup

Then downloaded expat from source and installed manually through the terminal:

http://sourceforge.net/projects/expat/?source=typ_redirect 

Deleted the old Git clones and started from scratch and it worked.
