### ISSUE TITLE
9gag plugin doesn't work

### ISSUE THREAD

**Issue by Akamaru** [yagop/telegram-bot#300]
*** lua: plugins/9gag.lua:9: bad argument #1 to 'random' (interval is empty)
http://api-9gag.herokuapp.com/ is empty

**Comment by yagop** [comment]
9Gag changed the HTML of the mobile version, fortunately the desktop version still serve images on the HTML. I changed the code of [9gag-api](http://api-9gag.herokuapp.com/) and its working.
