### ISSUE TITLE
Change telephone number [Issue]

### ISSUE THREAD

**Issue by JoseteRico** [yagop/telegram-bot#301]
Hello, I have been trying to change the mobile number.

Steps I tried:
- Removing telegram-cli folder from $Home. (worked and asked for a new number but when I try to restart the bot, it booted again the old number)
- Reinstalling tg lib.
- Reinstalling telegram-bot.

None worked :(

Anyone knows? Cheers.

**Comment by poshl000** [comment]
Just remove hidden .telegram-bot foldel in your home directory
