### ISSUE TITLE
libevent error

### ISSUE THREAD

**Issue by kirasir1** [yagop/telegram-bot#303]
When I tried to install bot on Raspberry Pi, i had error
`configure: error: no libevent found`
After installing libevent from official site, error appeared again.

**Comment by Bostrot** [comment]
try this: `sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make unzip git redis-server g++ libjansson-dev libpython-dev expat libexpat1-dev`
