### ISSUE TITLE
Allow disabling plugins

### ISSUE THREAD

**Issue by mrvdb** [yagop/telegram-bot#32]
I'm contemplating writing something which allows disabling plugins. This would make deployment (for me at least) a lot easier.

Something along these lines:
- move bot/config.json to /etc/config.json.sample
- write instructions for user to create a config.json file
- have a construct in the config file which allows  to disable plugins, for example, something like:

```
...
"disable" : {
    "youtube.lua": true,
   "rae.lua"
},
...
```

And have the loading of plugins and the `!reload` command use that.

Thoughts?

**Comment by yagop** [comment]
Allow disabling plugins is done in #45
