### ISSUE TITLE
Plugin Weather

### ISSUE THREAD

**Issue by robotrono** [yagop/telegram-bot#322]
Por ahí el plugin de Weather ha incluido una Key para poder utilizar la API, como se podría actualizar este plugin? 

http://openweathermap.org/faq#error401

Q: API calls return an error 401
A: Starting from 9 October 2015 our API requires a valid APPID for access. Note that this does not mean that our API is subscription-only now - please take a minute to register a free account to receive a key.

**Comment by robotrono** [comment]
Solo hay que agregar esto al final de cada petición:

```
http://api.openweathermap.org/data/2.5/forecast/city?id=524901&APPID=1111111111 
```

**Comment by yagop** [comment]
Despite of I can perfectly speak Spanish, its much better to speak English on issues.

Fixed https://github.com/yagop/telegram-bot/commit/c1a20c63c17fbf6d5862e2ded1b7c80c76b7f037
