### ISSUE TITLE
Plugin RSS

### ISSUE THREAD

**Issue by robotrono** [yagop/telegram-bot#324]
Al parecer no me llega a funcionar el plugin RSS, puedo agregar el enlace pero no me funciona a la hora de syncronizar no me muestra los items del RSS:

Mensaje de consola:
```
Chat Pruebita marked read 1 outbox and 0 inbox messages
Preprocess      stats
Saving user     user:89071709
msg matches:    ^!rss (sync)$
[17:57]  Pruebita Akira Perez >>> !rss sync

```

**Comment by TiagoDanin** [comment]
To better support, write in English. ;)
Verify that the "regit" this running or if was added site rss.
If not use the terminal: redis-server

**Comment by rockneurotiko** [comment]
`RSS` plugin works (I'm using it every day), but `!rss sync` don't send you the links, just force to get new values (by default it checks every 5 minutes, with sync you force it to check in that moment)

The misconception is because this plugin is a rss subscription plugin, not a rss reader plugin.
