### ISSUE TITLE
I'm created a group and bot kicked me

### ISSUE THREAD

**Issue by aminaleahmad** [yagop/telegram-bot#328]
hello
i'am created a group with my bot and my typing a message in the group bot kicked me please help

**Comment by Benjarobbi** [comment]
Then dont make a bot, and a group.

**Comment by aminaleahmad** [comment]
what??

**Comment by parham-q** [comment]
!unblock @hobab7
Help me

**Comment by parham-q** [comment]
i'am created a group with my bot and my typing a message in the group bot kicked me please help
