### ISSUE TITLE
plugins for forums and yotube 

### ISSUE THREAD

**Issue by drig0** [yagop/telegram-bot#331]
plugins to receive notification of forums and youtube 
example ( http://forum.xda-developers.com/android/apps-games )

**Comment by Benjarobbi** [comment]
already exist, look into rss

**Comment by drig0** [comment]
it is possible to add a youtube channel rss ?

**Comment by Akamaru** [comment]
!rss sub http://www.youtube.com/feeds/videos.xml?channel_id=CHANNELID

**Comment by drig0** [comment]
@Akamaru  me of a mistake  :   Error while doing the petition to

**Comment by drig0** [comment]
@Akamaru  thnks worked
