### ISSUE TITLE
Not working on Super Groups

### ISSUE THREAD

**Issue by cizaquita** [yagop/telegram-bot#347]
The bot is not working in super groups chats

**Comment by Josepdal** [comment]
https://github.com/yagop/telegram-bot/tree/supergroups

**Comment by tman862** [comment]
Supergroups aren't working with the latest pull from https://github.com/vysheng/tg, the bot will output the message with the pull @ 2b45dd6 but gives a nil for receiver and no plugins work. The latest of https://github.com/vysheng/tg @160231b it gives no output when a message is received, also no plugins work as well.

**Comment by GLAarmy** [comment]
how can fix this problem?? my bot is dont work to super group give help @Josepdal @cizaquita @tman862 @PotHix @joenio
