### ISSUE TITLE
send file 

### ISSUE THREAD

**Issue by drig0** [yagop/telegram-bot#349]
hello, I am trying to make the bot send files to me
these files are on the data folder,, along with : moderation.json, config.lua
his name is android.apk,,,

this and the command that I have::

-------------------------------------------------------------------------------------------------------------------
local function run(msg, matches)
send_document(receiver, 'data/android.apk', ok_cb, false)
end
    
      return {
 description = "send file", 
 usage = "/file ",
 patterns = {
 "^/file",
 "^!file"
 }, 
 run = run 
}

-----------------------------------------------------------------------------------------------------------

but he did not send the file
what could be wrong?

**Comment by Brawl345** [comment]
you forgot
local receiver = get_receiver(msg)
before send_document

**Comment by drig0** [comment]
@Brawl345  work 
works, very thank you master

**Comment by Brawl345** [comment]
Don't forget to close the issue ;)
