### ISSUE TITLE
Use command stack

### ISSUE THREAD

**Issue by malishev** [yagop/telegram-bot#37]
In some cases bot crashes because the previous task is not completed yet (for example, see https://github.com/yagop/telegram-bot/issues/36).
```
[52%Up]> telegram-cli: tgl/queries.c:1635: send_part: Assertion `f->part_size == x' failed.
```

I suggest adding command stack, something like `peer|command|timestamp`, so that all commands will be executed successively.

**Comment by yagop** [comment]
I don't know if the problem is in [tg](https://github.com/vysheng/tg) or in my bot but "DDoS" is not common.

**Comment by malishev** [comment]
Well, i'm sure you'll encounter this problem sooner or later

**Comment by yagop** [comment]
Sometimes tg crashes, I set it as an init service, so it restarts automatically...
