### ISSUE TITLE
Can't install - requires lua 5.1

### ISSUE THREAD

**Issue by IBaklanov** [yagop/telegram-bot#377]
Trying to install on two servers (one existing, one just launched) and getting the same error.

First, I install all dependencies  with `sudo apt-get update; sudo apt-get upgrade -y --force-yes; sudo apt-get dist-upgrade -y --force-yes; sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev libjansson* libpython-dev make unzip git redis-server g++ -y --force-yes && git clone https://github.com/yagop/telegram-bot.git && cd telegram-bot` without any problem.

Then I launch `./launch.sh install` and get the following error:

`...
Updating manifest for /tmp/telegram-bot/.luarocks/lib/luarocks/rocks
luasocket 3.0rc1-2 is now built and installed in /tmp/telegram-bot/.luarocks (license: MIT)

Installing https://rocks.moonscript.org/oauth-0.0.6-1.src.rock...
Using https://rocks.moonscript.org/oauth-0.0.6-1.src.rock... switching to 'build' mode

Missing dependencies for oauth:
lbase64

Using https://rocks.moonscript.org/lbase64-20120820-1.src.rock... switching to 'build' mode

Missing dependencies for lbase64:
lua ~> 5.1

Error: Failed installing dependency: https://rocks.moonscript.org/lbase64-20120820-1.src.rock - Could not satisfy dependency: lua ~> 5.1
Error. Exiting.`

Why does it require lua 5.1? I tried running `apt-get install lua5.1` and then re-running launch.sh, but with no luck :(

**Comment by sviat9440** [comment]
some there
