### ISSUE TITLE
Crash after sending command in supergroups

### ISSUE THREAD

**Issue by Ale32bit** [yagop/telegram-bot#403]
here's the error

telegram-cli: tgl/structures.c:997: tglf_fetch_message_media_new: Assertion `0' failed.

**Comment by Benjarobbi** [comment]
tg-cli isn't supported anymore. Please change to the bot api. 
Maybe you take a look into @RememberTheAir's Repo (GroupButler Bot).

Have a nice day,
Ben.

**Comment by Ale32bit** [comment]
@Benjarobbi I wanted to make a bot using tg client, no bots
Thanks anyway

**Comment by Benjarobbi** [comment]
Yes, of course I understand you. Maybe run it on Ubuntu instead.

**Comment by Ale32bit** [comment]
It runs on my raspberry Pi (Raspbian based on Debian)

**Comment by Benjarobbi** [comment]
There it should work?!
I host mine personal account on my Raspi too.

**Comment by Ale32bit** [comment]
anyway i mean using a telegram client, not using telegram bots (from BotFather)

**Comment by Benjarobbi** [comment]
Yes, I know.

**Comment by Ale32bit** [comment]
soo, your link was useless
