### ISSUE TITLE
Prevent messages from being marked as read

### ISSUE THREAD

**Issue by Turakar** [yagop/telegram-bot#43]
Hello,

I've deployed your program on my raspi, but I have the problem, that my raspi marks my messages as read all the time, althoug I didn't read them at all. It is clear to me why this happens, but I don't know how to prevent the bot from doing this. Is there a simple way to fix this? (Maybe you can only mark messages as read to which a pattern matches)

**Comment by yagop** [comment]
If you want to do now you have to comment this line https://github.com/yagop/telegram-bot/blob/master/bot/bot.lua#L19
I have the bot with a dedicated number so I dont have this problem, but you are right, the best is mark as read those messages which produces a response or matches a pattern. However there are some plugins like `stats` that matches every msg.

**Comment by Turakar** [comment]
Maybe a plugin can return the string and optional a boolean, if the message shall not be marked as read. The default would be false and special plugins like stats would have to return true explicitly.

**Comment by yagop** [comment]
Its done in 5eb58870d26761aa6b85dcc5e3db888562702087 but if you have enabled __stats__ plugin it will mark as read every message. Comment [this](https://github.com/yagop/telegram-bot/blob/master/bot/bot.lua#L80) line if you want to enable stats and don't mark messages as read.
