### ISSUE TITLE
rae not working

### ISSUE THREAD

**Issue by n4txo** [yagop/telegram-bot#48]
It seems that the call to the api http://dulcinea.herokuapp.com/api/?query= in plugins/rae.lua is not working.

"Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details."

**Comment by yagop** [comment]
Yes, I know the problem. The [application](https://github.com/javierhonduco/dulcinea) is done by @javierhonduco but as I know he is on exams and he must be studding.

**Comment by n4txo** [comment]
Ok, thanks for the update.

Maybe a call to buscon.drae... instead a call to an owned application?

**Comment by javierhonduco** [comment]
Hi @n4txo,
Sorry for the inconvenience. I'll fix it as soon as I can.
As I said to @yagop once, one alternative approach would be calling the ruby library (https://github.com/javierhonduco/nebrija) from lua. In fact that's the library that https://github.com/javierhonduco/nebrija uses underneath. Feel free to deploy the app if you want to continue using the current approach from today :)

**Comment by n4txo** [comment]
Ok, thanks

•n•

**Comment by javierhonduco** [comment]
It works 0K now. :)

**Comment by n4txo** [comment]
Thanks.

**Comment by yagop** [comment]
Thanks @javierhonduco :heart_eyes:
