### ISSUE TITLE
Add Wikipedia Plugin?

### ISSUE THREAD

**Issue by Brawl345** [yagop/telegram-bot#49]
A wikipedia plugin would be nice! It would send the first paragraph from the wikipedia article for example.
Documentation: https://en.wikipedia.org/w/api.php
https://www.mediawiki.org/wiki/API:Main_page

**Comment by rutgerh** [comment]
There is one made already by asdofindia;
https://github.com/asdofindia/telegram-bot/blob/master/plugins/wiki.lua

**Comment by Brawl345** [comment]
Whoa, nice! Thanks!

**Comment by PotHix** [comment]
What about close this one? :)

**Comment by Brawl345** [comment]
Yeah, but it's not integrated in yagops bot, thats why I left it open. I will close this now :)
