### ISSUE TITLE
msg.from.id returns nil

### ISSUE THREAD

**Issue by P0L4C0** [yagop/telegram-bot#52]
Hi, I'm unable to use the msg.from.id in my plugin, am I missing something?

Thanks in advance, greetings from Brazil.

**Comment by Electrofenster** [comment]
you should send us a little code from your plugin. We don't have a magic glass ball to see your function. But this should work as example:
```lua
function get_id_from_msg(msg)
    return msg.from.id;
end
```

**Comment by P0L4C0** [comment]
Hi,

Sorry, follows the details:

When I use the following, I get the bot´s ID and it works flawlessly:

    local chat_id = tostring(msg.to.id)

But when I try to get the user information (tried all the ways below) It returns nil:

    local chat_id = tostring(msg.from.id)
    local user_name = get_name(msg)
    local user_last_name = msg.from.last_name
    local user_print_name = msg.from.print_name

Do I have to declare something in order to make it work? I tried all the above but none of them work, even though they do work on the stats plugin:

Thanks again, This is for a university assignment, I´ll submit the plugin once I´m done.

**Comment by Electrofenster** [comment]
what does this function give you back? 
```lua
is_chat_msg(msg)
```

when it return false try this:
(I don't have a runny machine here to test this but it should work)
```lua
vardump(msg)
```

with this function you could see all the possibilities what you can access from ```msg ```

When the bot recieve a message the vardump function is called [automatically](https://github.com/yagop/telegram-bot/blob/master/bot/bot.lua#L10)

or you can try this to find out the msg.
```lua
  if msg_valid(msg) == false then
    print ("No valid message!")
  end
```

take a look at [this](https://github.com/yagop/telegram-bot/blob/master/bot/bot.lua) file to get basic information about the bot.

I hope some of these things help you ;)
