### ISSUE TITLE
Drop secret chats

### ISSUE THREAD

**Issue by malishev** [yagop/telegram-bot#58]
As the bot cannot into secret chats, i suggest dropping them in the very beginning. 

This may help to get rid of some console errors: 
![2015-02-04 22 30 03](https://cloud.githubusercontent.com/assets/2178368/6047874/68bd84fa-acbd-11e4-9a9c-1c6842f80784.png)

And prevent some **known** secret chats related errors in tgl, such as:
[`tglf_fetch_encrypted_message: Assertion new_id == id' failed`](https://github.com/vysheng/tg/issues/381) or [`tglf_fetch_encrypted_message: Assertion 'skip_type_any`](https://github.com/vysheng/tg/issues/410), etc

**Comment by yagop** [comment]
Thanks for reporting. This happens when an user opens a secret chat, isn't it?
With the latest tg version, they arrive to the bot but he cant answer, I will investigate this.

**Comment by malishev** [comment]
Maybe, i cannot notice any correlation. But it has just happened one more time and it sucks 😔

**Comment by yagop** [comment]
Fixed time ago.
