### ISSUE TITLE
Reenviar mensajes a un usuario / Forward messages to any user

### ISSUE THREAD

**Issue by Felfa** [yagop/telegram-bot#59]
Buenas:

Estoy intentando escribir un plugin que sea capaz de **reenviar un mensaje** recibido al usuario que lo haya ejecutado.

Me explico, un plugin que ejecute el comando de Telegram-CLI: **fwd user msg_id** siendo *user* el valor que devuelva *msg.from.print_name*, y *msg_id* un número entero que identifique un mensaje cualquiera que haya recibido el cliente.

He probado usando la función: **fwd_msg(msg.from.print_name, 4, ok_cb, false)**, función que he visto dentro de la documentación de tg, pero no devuelve ningún mensaje (el 4 es un ejemplo). Aparentemente no es la función correcta. ¿De qué forma puedo reenviar mensajes a través de un plugin?

Gracias :)

==
Summary: how can I forward messages from a plugin?

**Comment by yagop** [comment]
El problema es que estás pasando el segundo parámetro incorrecto, tiene que ser el id del mensaje (suele ser un número largo), tienes que obtenerlo con `msg.id` y guardarlo para usarlo después.

Hay un [ejemplo](https://github.com/vysheng/tg/blob/master/test.lua#L91) en el repo de tg en el que usa la función `fwd_msg`.

**Comment by JorgeDDW** [comment]
Can you share your plugin Felfa?
