### ISSUE TITLE
gcc: internal compiler error: Killed (program cc1)

### ISSUE THREAD

**Issue by loskiq** [yagop/telegram-bot#60]
gcc -I. -I. -g -O2  -I/usr/local/include -I/usr/include -I/usr/include -I/usr/include/lua5.2   -DHAVE_CONFIG_H -Wall -Wextra -Werror -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -iquote ./tgl -c -MP -MD -MF dep/auto/auto.d -MQ objs/auto/auto.o -o objs/auto/auto.o auto/auto.c
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
make: *** [objs/auto/auto.o] Error 4

**Comment by yagop** [comment]
You are compiling telegram-cli? Maybe you don’t have enough memory to compile.
