### ISSUE TITLE
Request: plugin google translator

### ISSUE THREAD

**Issue by valessiobrito** [yagop/telegram-bot#69]
Inpired in https://github.com/fermino/WhatsBot/commit/ff30704a9699e0da33906fa453d74c17bbd706d3

Google translator plugin.

**Comment by franckuestein** [comment]
Translation plugin was added the 14th of march closing the issue #76: https://github.com/yagop/telegram-bot/blob/master/plugins/translate.lua

Review it ;)

**Comment by valessiobrito** [comment]
Thanks a lot!
