### ISSUE TITLE
Request: plugin setting to set response message to the user

### ISSUE THREAD

**Issue by valessiobrito** [yagop/telegram-bot#72]
A user to call a plugin command in the group, you can get your answer in private/direct message.
The ability to set some plugins to direct the response outside the group which the user requested message. Eg.

In group "Telegram" the user "Bet" request plugin " !help " or  " !img ",  the response return in private message. Not in group.

**Comment by yagop** [comment]
Sorry but this should be implemented by the creator of the plugin. There is a simple way that is use `send_msg(receiver, text, ok_cb, false)` inside the plugin and use `'user#id'..msg.from.id` as `receiver`
