### ISSUE TITLE
Request: plugin for Google translate

### ISSUE THREAD

**Issue by DrStranger** [yagop/telegram-bot#76]
Please :)

**Comment by yagop** [comment]
Google translate API is a paid service as I know. It requires authentication, see yourself:
[https://www.googleapis.com/language/translate/v2?q=hello%20world&source=en&target=es](https://www.googleapis.com/language/translate/v2?q=hello%20world&source=en&target=es)

```json
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```
But it can be done by querying [translate.google.com](http://translate.google.com) like this:
[https://github.com/koreader/koreader/blob/master/frontend/ui/translator.lua ](https://github.com/koreader/koreader/blob/master/frontend/ui/translator.lua)

**Comment by malishev** [comment]
No big deal, just some regexp magic.

`http://translate.google.com/translate_a/t?client=t&text=EXAMPLE&sl=auto&tl=LANG`

Example:
http://translate.google.com/translate_a/t?client=t&text=example&sl=auto&tl=ru

Example with sed (try executing in console):
```bash
wget -U "Mozilla/5.0" -qO - "http://translate.google.com/translate_a/t?client=t&text=EXAMPLE&sl=auto&tl=ru" | sed 's/\[\[\[\"//' | cut -d \" -f 1
```
