### ISSUE TITLE
how to use send_photo() to send sticker (webp file)

### ISSUE THREAD

**Issue by ariefbayu** [yagop/telegram-bot#78]
The following codes is purposed to send custom sticker. However, I'm not sure why send_photo() doesn't deliver the image :(.

    function run(msg, matches)

	print ("processing sticker " .. matches[1])

	local response = ""
	local rootpath = "/home/ariefbayu/telegram-bot/stickers/reps/"

	local sticker_pairs = {
		["smile"]="ladysmile",
		["awesome"]="ras-awesome",
		["sad"]="belu-sad"
	}

	print (" matched: " .. sticker_pairs[ matches[1] ])

	  for k, v in pairs(sticker_pairs) do
	    print("checking sticker", k)

	    if k == matches[1] then

			if messageToAllowed(msg.to.id) == false then

				return ""

			end

			local receiver = get_receiver(msg)
			local file_path = rootpath .. sticker_pairs[ matches[1] ] .. ".webp"
			print(file_path)
			if file_exists(file_path) == true then

				response = matches[1]

				local cb_extra = {
					file_path = file_path,
					cb_function = cb_function,
					cb_extra = cb_extra
				}
				-- Call to remove with optional callback
				-- send_photo(receiver, file_path, rmtmp_cb, cb_extra)

				send_photo(receiver, file_path, ok_cb, cb_extra)
			else
				response = "sticker is missing..."
			end
			break

	    end
	    
	  end

        return response
    end

    function messageToAllowed(id)
	local response = true

	return response
    end

    return {
        description = "load custom stickers", 
        usage = "/sticker [sticker-name]",
        patterns = {
    		    "^/sticker (.*)$"
    	    }, 
        run = run 
    }

**Comment by yagop** [comment]
It would be nice if the example code is much more simple. I coded this and isnt working, maybe tg doesn't support sending stickers at the moment.

```lua
do

function run(msg, matches)
  local file_path = '/tmp/roto2.webp'
  local receiver = get_receiver(msg)
  send_document(receiver, file_path, ok_cb, false)
end

return {
    description = "", 
    usage = "",
    patterns = {
      "^!webp$"
    }, 
    run = run 
}

end
```

**Comment by ariefbayu** [comment]
thanks, send_document is the solution!
my code works, while, admittedly, need a lot of fix. LUA wasn't my thing :D
