### ISSUE TITLE
plugin for Database query

### ISSUE THREAD

**Issue by larknart** [yagop/telegram-bot#81]
is there any sample plugin that can connect to database (oracle, mysql) and do the query?

**Comment by yagop** [comment]
No, sorry.

**Comment by Cameri** [comment]
@larknart You are better off writing a RESTful API that interfaces with the database and then consume that API from the bot.
It should not be the responsibility of the bot to connect to the database directly, IMHO.

**Comment by yagop** [comment]
I don't see the point of writing a RESTful API and calling from the bot. That will take more lag, best way is to call DB by the bot itself. You can use [LuaSQL](http://keplerproject.github.io/luasql/doc/us/). I was working on it but don't know if at last I am going to release a version with DB support, installation would be harder than now.

Closed, if you really need a plugin with DB support, write your own.
