### ISSUE TITLE
Access removed from telegram

### ISSUE THREAD

**Issue by sander3991** [yagop/telegram-bot#82]
I wanted to change the number (user) the telegram bot was using. So I revoked access to the bot from my number. Now I can't setup a new number anymore. What can I do to fix this? Tried reinstalling it but that didn't do anything. Are the user settings saved elsewhere?

**Comment by TheReverend403** [comment]
remove ~/.telegram-cli/auth

**Comment by sander3991** [comment]
I've removed said file and restarted the bot, it has not prompted me to fill in a new number and it's still not functioning.

**Comment by TheReverend403** [comment]
Oh, my bad. Remove ~/.telegram-cli/auth, ~/.telegram-cli/secret and ~/.telegram-cli/state

**Comment by sander3991** [comment]
That did the trick thanks! Might be nice if this could be incorperated in a command when running the bot?

**Comment by yagop** [comment]
A command for deleting current session is bad, might crash. This should be done carefully by hand.
