### ISSUE TITLE
plugin to run the shell script

### ISSUE THREAD

**Issue by alting** [yagop/telegram-bot#86]
Good day, yagop!
Can I ask you to write a plugin to run the shell script?
input: name of the file, like miui_MI3WMI4W_5.3.13_553221c9f5_4.4.zip
must: run shell or lua script, who can generate a link for download file:

#!/bin/bash
nowd=`date '+%y.%m.%d' | sed 's/0//' | cut -c 2-`
cd /home/user/ROMS/
axel http://bigota.d.miui.com/$nowd/miui_MI3WMI4W_5.3.13_553221c9f5_4.4.zip

thank you in advance!

**Comment by yagop** [comment]
You have this function https://github.com/yagop/telegram-bot/blob/master/bot/utils.lua#L162
But use at your own risk, if you need an user param for the command, first check if is sudo user and/or sanitize it. The user may execute code on your machine.

**Comment by alting** [comment]
I'm sorry, but I have enough experience to implement this feature ..

**Comment by yagop** [comment]
You mean don’t have enough experience, do you?

The name of the file must be written by the user who execute the command? Or is in the shell script?

**Comment by alting** [comment]
I think is in the shell script with any variables

**Comment by yagop** [comment]
I am sorry, I cant write plugins for everybody.
