### ISSUE TITLE
Latest version crashes

### ISSUE THREAD

**Issue by SyRenity** [yagop/telegram-bot#87]
The version crashes with:
> telegram-cli: tgl/queries.c:148: tglq_send_query_ex: Assertion `DC->auth_key_id' failed.
SIGNAL received
h./tg/bin/telegram-cli(print_backtrace+0x20)[0x4437d0]
./tg/bin/telegram-cli(termination_signal_handler+0x64)[0x443854]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7f711324bd40]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39)[0x7f711324bcc9]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f711324f0d8]
/lib/x86_64-linux-gnu/libc.so.6(+0x2fb86)[0x7f7113244b86]
/lib/x86_64-linux-gnu/libc.so.6(+0x2fc32)[0x7f7113244c32]

Happens on Ubuntu 14.04.

Anyone else has it?

**Comment by Goodgy** [comment]
Does running telegram ( Without bot ) return the same?

**Comment by franckuestein** [comment]
Can you try running the following command on the /tg folder and post here what happen?
> bin/telegram-cli -k tg-server.pub

**Comment by yagop** [comment]
This is a [tg](https://github.com/vysheng/tg) question, closed.
