### ISSUE TITLE
Twitter 401

### ISSUE THREAD

**Issue by Thom7** [yagop/telegram-bot#88]
Bot is working great, all but the twitter part.
I've installed oauth and other dependancies. Created an app on twitter, generated keys and secrets, etc.
Gave the app permissions, but still getting 401 errors.
Tried changing system time, callback, or none, giving login perms to app, but still unable to post.

Any ideas?

**Comment by yagop** [comment]
Any errors in the console output?

**Comment by Thom7** [comment]
I'm not too familiar with the terminal yet, how would I get the output?

**Comment by Thom7** [comment]
Unsure what the problem was, it was solved by disabling, deleting, reuploading, and re-enabling the plugin, followed by remaking the app on twitter.
