### ISSUE TITLE
How do i get username ?

### ISSUE THREAD

**Issue by bypassfuture** [yagop/telegram-bot#90]
Hi ,

Telegram-bot is great & really helpful !

Now i know **user_info** command in tg can give **username** . So how do i get username in telegram-bot , is there a interface in telegram-bot execute tg commands ( like user_info ) , or are there any other means to achieve this ?

thanks !

**Comment by yagop** [comment]
Yes, check this: https://github.com/vysheng/tg/blob/master/README-LUA

If you want to get hte username from a msg, check this telegram-bot function: https://github.com/yagop/telegram-bot/blob/master/bot/utils.lua#L183

**Comment by bypassfuture** [comment]
Thanks , really appreciate it : )
