### ISSUE TITLE
Hubot integration

### ISSUE THREAD

**Issue by valessiobrito** [yagop/telegram-bot#95]
Integration with Hubot: https://hubot.github.com

**Comment by yagop** [comment]
This project started as standalone bot, other bots aren't supported now. Maybe in a future...

To integrate Telegram with hubot, you can use [zenitraM/hubot-tg](https://github.com/zenitraM/hubot-tg).
Also [voiser/telegram-for-robots](https://github.com/voiser/telegram-for-robots) is an interesting proyect to checkout.
