### ISSUE TITLE
Problema al configurar upstart

### ISSUE THREAD

**Issue by loboaureo** [yagop/telegram-bot#96]
No tengo casi idea de linux, pero he conseguido mediante apt-get instalar upstart en mi raspberry pi con raspbian.

La cuestion es que no me quedan claras las instrucciones a seguir de la pagina principal.
$ sed -i "s/yourusername/$(whoami)/g" etc/telegram.conf
$ sed -i "s_telegrambotpath_$(pwd)_g" etc/telegram.conf

Supongo que yourusername es una variable que debo cambiar por la que se ajuste en mi configuracion, pero no tengo claro si es mi usuario de linux, el id de mi bot en telegram, el nombre de mi bot en telegram o que.

Igualmente me pasa con el pwd, que no se si es un literal y lo dejo asi, o tengo que cambiarlo por algun password.

**Comment by yagop** [comment]
`pwd` es un comando (para saber el directorio actual).
Ambos hay que dejarlos tal y como están, sed, remplazará las variables del fichero por las salidas del comando. Simplemente copia y pega los comandos.

**Comment by loboaureo** [comment]
Muchas gracias por la rapida respuesta. Un gran trabajo
