### ISSUE TITLE
Peticion: Actualizacion automatica

### ISSUE THREAD

**Issue by loboaureo** [yagop/telegram-bot#97]
Estaria bien que el bot y los plugins se actualizaran con algun tipo de regularidad y de manera transparente para el usuario.

**Comment by yagop** [comment]
Que se actualize, implica reiniciar el cliente y puede que falle, tanto como hacerlo trasparente no me parece buena idea. Aún así, puede ser buena idea, tener un comando para actualizarlo y reiniciar.

**Comment by JorgeDDW** [comment]
Solo necesitas revisar el log del proyecto en Github y comparar con tu version, si hay un cambio: descargar y compilar.
