### ISSUE TITLE
Some command executed but no outpot posted back

### ISSUE THREAD

**Issue by psycholyzern** [yagop/telegram-bot#98]
```!plugins``` reload does load in ```./launch``` but nothing posted back to me. I post ```!plugin reload``` and it just double tick and nothing happened. But in ```./launch.sh```, it does reload the config.

This happened after I renaming a plugin. This problem does not go away even after I renaming the plugin back to its original name.

**Comment by ollpu** [comment]
You should have a look at a couple things:
 - Check that the `plugins` plugin is enabled by manually reading the `data/config.lua`. Check that the enabled_plugins sections contains the current name of the `plugins` plugin. If not, add it there.
 - Have a look at the console when the bot is started or when you call `!plugins reload`, if you see an error, it usually means that some plugin has malformed code and cannot be loaded. (In this case, the bot will return nothing to the chat)

**Comment by psycholyzern** [comment]
I redownload the script from git and all work again.Thanks
